### PR TITLE
Fix a bug in DocumentRoot::coalesceIndexPath

### PR DESCRIPTION
**Pull request by bzrk**
if the requesturi is "/", then clear the filesystem cache for
all index files before you get the file statistics for each index file

### CODE REVIEW

**Comment by kelunik** [comment]
Hey @bzrk, I guess you placed a new file there and it wasn't served correctly due to an older cache entry?

**Comment by bzrk** [comment]
Hey @kelunik, thanks for the response. 
Yes i placed a new index.html file in the document root directory. But the server give me ever not modified status code.
I'm sure the the problem is not the Cache from DocumentRoot Object. You can see in the Testcase i started a new Server with an empty Cache. I hope you understand my English ;-)

**Comment by kelunik** [comment]
@bzrk Sorry for the long delay. Caching has been reworked in `amphp/file@^2`, so you can now simply pass a non-caching driver instead, see https://github.com/amphp/http-server-static-content/compare/v1.0.6...v1.0.7

**Comment by bzrk** [comment]
THX

**Pull request closed without merging**
