### PR TITLE
Test properly on PHP 7.4 and 8.0

### PR DESCRIPTION
**Pull request by bzikarsky**

### CODE REVIEW

**Comment by kelunik** [comment]
Thanks! We should look into migrating this to github actions.

Your current commit doesn't seem to be correctly linked to your account.

**Comment by bzikarsky** [comment]
Yes, I also wanted to followup with another MR from this branch: https://github.com/bzikarsky/http-server-static-content/tree/fix-http-server-ref

~The reason for this additional change is a PHP error which is thrown when the interface (defining `HttpServer`) is fulfilled with an alias `Server`~

Edit - taken from IRC:

Me:
> Worth mentioning, we had interesting errors today when I roled out an amp/http-server upgrade
>  PHP Fatal error: (userId=0, url=/code/cli) Could not check compatibility between Amp\Http\Server\StaticContent\DocumentRoot::onStart(Amp\Http\Server\Server $server): Amp\Promise and Amp\Http\Server\ServerObserver::onStart(Amp\Http\Server\HttpServer $server): Amp\Promise, because class Amp\Http\Server\Server is not available in <path>
>Fixing DocumentRoot from "Server" to "HttpServer" fixed it. It may be worth to upgrade `http-server-static-content` as it hasn't seen a release in quite a while

Kelunik
> Hm, why is the alias not loaded?

Me
> I assume it's this: https://softwareengineering.stackexchange.com/a/340005 -- Nothing triggers the autoloader for `Amp\Http\Server\Server ` - the alias never is loaded.

With this in mind, simply testing with PHP7.4 will not surface the error. I suggest that we treat this as a separate issue, which has to be solved in `amp//http-server`. Maybe I'll find some time to write a verifying test.

**Comment by bzikarsky** [comment]
And yes, this mail is not associated with my github account, will fix this later. Thanks for bringing it up.

Edit: Fixed

**Comment by kelunik** [comment]
Closing, because we've already moved to GitHub Actions on the v2 branch.

**Pull request closed without merging**
