### PR TITLE
Add an optional $stripFromPath argument

### PR DESCRIPTION
**Pull request by Pato05**
A simple patch which adds the $stripFromPath optional argument.

### CODE REVIEW

**Comment by kelunik** [comment]
IMO this should be its own middleware, so it can also be reused for other things and to reduce the complexity of this handler.

**Comment by Pato05** [comment]
But it reduces complexity for this job, otherwise you would use a Middleware, which would be more complex

**Comment by kelunik** [comment]
It's slightly more complex to configure then, but doesn't mix concerns and is reusable.

**Comment by Pato05** [comment]
Well, the choice is up to you, for me this could be very useful and doesn't increase the request handler's complexity a lot. If you decide not to merge, we can close this PR

**Review by trowski — CHANGES_REQUESTED** [review]
I too think this should be a middleware.

**Pull request closed without merging**
